service: project-serverless # Choose your project name. It is up to you.

useDotenv: true

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-associate-waf

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 10
  region: us-east-1
  apiGateway: 
   minimumCompressionSize: 1024

package:
  excludeDevDependencies: true
  patterns:
    - '!.angular/**'
    - '!.github/**'
    - '!.vscode/**'
    - '!coverage/**'
    - '!libs/**'
    - '!src/**'
    - '!node_modules/**'
    - '!e2e/**'
    - '!firebug-lite/**'
    - '!.eslintignore'
    - '!.eslintrc.base.json'
    - '!.eslintrc.json'
    - '!.gitignore'
    - '!.prettierignore'
    - '!.prettierrc'
    - '!jest.config.app.ts'
    - '!jest.config.ts'
    - '!jest.preset.js'
    - '!nx.json'
    - '!README.md'
    - '!server.ts'
    - '!tailwind.config.js'
    - '!tsconfig.app.json'
    - '!tsconfig.base.json'
    - '!tsconfig.editor.json'
    - '!tsconfig.json'
    - '!tsconfig.server.json'
    - '!tsconfig.spec.json'
    - node_modules/@vendia/**
    - node_modules/aws-serverless-express/**
    - node_modules/binary-case/**
    - node_modules/type-is/**
    - node_modules/media-typer/**
    - node_modules/mime-types/**
    - node_modules/mime-db/**

custom:
  serverless-offline:
    noPrependStageInUrl: true
    printOutput: true
  contentCompression: 1024
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY /{proxy+}
      - http: ANY /